# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

In [1]:
import numpy as np
from matplotlib import pyplot as plt

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [2]:
#Solution
age=np.random.randint(10,22,21)
age



array([10, 20, 19, 19, 17, 10, 20, 21, 13, 16, 17, 14, 21, 16, 18, 12, 15,
       20, 19, 17, 18])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [3]:
# Solution
length=np.arange(1,50,2)
print(length)
len(length)



[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


25

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [4]:
# Solution
lin=np.linspace(4,7,27)
lin


array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [5]:
# Solution

mat=np.random.random((5,4))
mat_round=np.round(mat,2)
mat_round

array([[0.79, 0.62, 0.5 , 0.6 ],
       [0.7 , 0.73, 0.26, 0.74],
       [0.26, 0.08, 0.75, 0.07],
       [0.32, 0.96, 0.6 , 0.85],
       [0.58, 0.79, 0.43, 0.89]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [6]:
# Solution
rand=np.random.randint(5,15,(5,5))
rand


array([[ 7,  6, 11,  8,  9],
       [10, 13, 12,  5, 11],
       [13, 11,  8,  7,  8],
       [14, 12,  8, 12,  7],
       [10, 12, 11, 14,  7]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [7]:
# Solution

oned_array=np.random.randint(0,1,(1,20))
print(oned_array)
print(type(oned_array))
print(len(oned_array))
oned_array.dtype


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
<class 'numpy.ndarray'>
1


dtype('int32')

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [30]:
# Solution
twod_array=np.eye(3)
print(twod_array)
print(type(twod_array))
print(twod_array.shape)
twod_array=twod_array.astype('float32')
twod_array.dtype

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>
(3, 3)


dtype('float32')

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [9]:
# Solution
matrix=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(matrix)
print(matrix.shape)
type(matrix)
print(matrix.dtype)

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
(5, 5)
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [10]:
# Solution
shape=matrix.shape
r=shape[0]
r1=int(r/2)
c=shape[1]
c1=int(c/2)
print(matrix[r1,c1])



3


#### 10. Print the all the elements of 3rd row of the matrix

In [11]:
# Solution
matrix[2:3,:]



array([[ 5,  7,  3, 76,  3]])

#### 11. Print the all the elements of 4th columns of the matrix

In [12]:
# Solution
matrix[:,3:4]



array([[34],
       [65],
       [76],
       [54],
       [ 5]])

#### 12. Print the 4 corner pixels of the matrix

In [13]:
# Solution
shape=matrix.shape
r=shape[0]
c=shape[1]
print("4 Corner Pixels ofthe matrix are: ",matrix[0,0],matrix[0,c-1],matrix[r-1,0],matrix[r-1,c-1])

4 Corner Pixels ofthe matrix are:  9 45 23 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [14]:
# Solution 
m1=matrix[0:2,2:4]
m2=matrix[3:5,0:2]
m3=matrix[2:5,2:5]
print("m1 : \n",m1)
print("m2 : \n",m2)
print("m3 : \n",m3)

m1 : 
 [[50 34]
 [34 65]]
m2 : 
 [[ 7  8]
 [23 12]]
m3 : 
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [31]:
# Solution
m1=m1.ravel()
m2=m2.ravel()
m3=m3.ravel()
print(m1)
print(m2)
print(m3)

[50 34 34 65]
[ 7  8 23 12]
[ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction
https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b

In [16]:
# Solution
np.stack((m1,m2),axis=0)

array([[50, 34, 34, 65],
       [ 7,  8, 23, 12]])

In [32]:
np.stack((m1,m2),axis=1)

array([[50,  7],
       [34,  8],
       [34, 23],
       [65, 12]])

#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [17]:
# Solution
print("Addition: \n",m1+m2)
print("Subtraction: \n",m1-m2)
print("Multiplication: \n",m1*m2)
print("Division: \n",m1/m2)



Addition: 
 [57 42 57 77]
Subtraction: 
 [43 26 11 53]
Multiplication: 
 [350 272 782 780]
Division: 
 [7.14285714 4.25       1.47826087 5.41666667]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [18]:
# Solution
m1=matrix[0:2,2:4]
m3=matrix[2:5,2:5]
m3a=m3[1:,:2]
#print(m1.shape)
#print(m3a.shape)
#print(m1,m3a)
rem=np.concatenate((m1,m3a))
print(rem)
print(rem.shape)

[[50 34]
 [34 65]
 [ 6 54]
 [ 8  5]]
(4, 2)


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [19]:
# Solution
me1=m1.mean(axis=1)
print(m1.shape)
me1=me1.reshape((1,2))
print(me1.shape)
m4=np.concatenate((m1,me1))
print("Matrix 4 is :\n",m4)

(2, 2)
(1, 2)
Matrix 4 is :
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [20]:
# Solution
print(m3)
print(m4)

print(np.matmul(m3,m4))



[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]
[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]
[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [21]:
# Solution
print(matrix)
max_mean=max(matrix.mean(axis=0))
min_mean=min(matrix.mean(axis=0))
max_var=max(matrix.var(axis=0))
min_var=min(matrix.var(axis=0))
max_std=max(matrix.std(axis=0))
min_std=min(matrix.std(axis=0))
print("max_mean is : ", max_mean)
print("min_mean is : ", min_mean)
print("max_var is : ", max_var)
print("min_var is : ", min_var.round(2))
print("max_std is : ", max_std.round(2))
print("min_std is : ", min_std.round(2))

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
max_mean is :  46.8
min_mean is :  9.4
max_var is :  629.36
min_var is :  50.24
max_std is :  25.09
min_std is :  7.09


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [22]:
# Solution 
runs=np.array([['MSD',54,60,10,65],['Kholi',102,2,78,32],['Rohit',3,110,1,92],['Rahul',56,6,12,42],['Dhawan',12,8,22,11]])
balls=np.array([['MSD',50,42,22,78],['Kholi',95,8,65,43],['Rohit',9,100,7,101],['Rahul',27,3,11,31],['Dhawan',24,20,36,27]])
print(runs)
print(balls)

[['MSD' '54' '60' '10' '65']
 ['Kholi' '102' '2' '78' '32']
 ['Rohit' '3' '110' '1' '92']
 ['Rahul' '56' '6' '12' '42']
 ['Dhawan' '12' '8' '22' '11']]
[['MSD' '50' '42' '22' '78']
 ['Kholi' '95' '8' '65' '43']
 ['Rohit' '9' '100' '7' '101']
 ['Rahul' '27' '3' '11' '31']
 ['Dhawan' '24' '20' '36' '27']]


In [23]:
avg_runs=runs[:,1:]
avg_runs=avg_runs.astype('int32')
me1=avg_runs.mean(axis=1)
me1=me1.reshape(5,1)
avg=np.concatenate((runs,me1),axis=1)
print('The average runs in the given 4 matches are : \n',avg)
sortedsr=np.sort(me1)[::-1]
sortedsr

The average runs in the given 4 matches are : 
 [['MSD' '54' '60' '10' '65' '47.25']
 ['Kholi' '102' '2' '78' '32' '53.5']
 ['Rohit' '3' '110' '1' '92' '51.5']
 ['Rahul' '56' '6' '12' '42' '29.0']
 ['Dhawan' '12' '8' '22' '11' '13.25']]


array([[13.25],
       [29.  ],
       [51.5 ],
       [53.5 ],
       [47.25]])

In [37]:
strike_rate=balls[:,1:]
strike_rate=strike_rate.astype('int32')
me2=(avg_runs.sum(axis=1)/strike_rate.sum(axis=1))*100
me2=me2.reshape(5,1)
me2=me2.round(2)
strike=np.concatenate((balls,me2),axis=1)
print('The strike rate in the guven 4 matches are : \n',strike)
sortedsr=np.sort(me2)[::-1]
sortedsr

The strike rate in the guven 4 matches are : 
 [['MSD' '50' '42' '22' '78' '98.44']
 ['Kholi' '95' '8' '65' '43' '101.42']
 ['Rohit' '9' '100' '7' '101' '94.93']
 ['Rahul' '27' '3' '11' '31' '161.11']
 ['Dhawan' '24' '20' '36' '27' '49.53']]


array([[ 49.53],
       [161.11],
       [ 94.93],
       [101.42],
       [ 98.44]])

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [25]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
print(marks>50)
passed=(marks>50).sum()
print('Number of students passed are : ',passed)
failed=(marks<50).sum()
print('Number of students failed are : ',failed)

[ True  True False  True  True  True False  True  True False]
Number of students passed are :  7
Number of students failed are :  3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [26]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
passper1=(passed/len(marks))*100
mark_copy=marks.copy()
for i in range(len(mark_copy)):
    if mark_copy[i]>45 and mark_copy[i]<49:
        mark_copy[i]+=5
    elif mark_copy[i]>80:
        mark_copy[i]+=5
mark_copy[mark_copy>100]=100
passed1=(mark_copy>50).sum()
passper2=(passed1/len(mark_copy))*100

print('The Original marks are : ',marks)
print('The Updated marks are : ',mark_copy)
print('The Pass Percentage of Original marks is : ',passper1)
print('The Pass Percentage of Updated marks is : ',passper2)
print('The Increase in Pass Percentage is : ',passper2-passper1)

The Original marks are :  [65 84 47 56 89 98 48 77 80 39]
The Updated marks are :  [ 65  89  52  56  94 100  53  77  80  39]
The Pass Percentage of Original marks is :  70.0
The Pass Percentage of Updated marks is :  90.0
The Increase in Pass Percentage is :  20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [27]:
# Solution
    
import time
def lst():
    x=list(range(1,60000))
    y=list(range(1,60000))
    res=[]
    for i in range(len(x)):
        res.append((((x[i]**2)+8)/y[i]))
    
def npy():
    x=np.array(range(1,60000))
    y=np.array(range(1,60000))
    res=((x**2)+8)/y
    
start=time.time()
%time lst()
end=time.time()
print("Time taken for performing the list operation : ",end-start)
start1=time.time()
%time npy()
end1=time.time()
print("Time taken for performing the Numpy operation : ",end1-start1)


Wall time: 79.7 ms
Time taken for performing the list operation :  0.07965898513793945
Wall time: 40.2 ms
Time taken for performing the Numpy operation :  0.0401918888092041


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [28]:
# Solution



